db:
  url: jdbc:postgresql://localhost:5432/postgres
  username: postgres
  password: root

logging:
  level:
    root: INFO

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    url: jdbc:postgresql://localhost:5432/springdb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate

  messages:
    basename: messages